apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
   app: helooworld
spec:
  containers:
  - name: k8s-demo
    image: arjunachari12/k8s-demo
    ports:
    - name: nodejs-port
      containerport: 3000
