apiVersion: v1
kind: Pod
metadata: 
  name: pod3
spec:
  containers:
  - name: webserver
    image: nginx
    ports: 
    - containerPort: 80
  - name: webwatcher
    image: afakharany/watcher:latest
