apiVersion: v1
kind: Deployment
metadata: 
  name: redis-deployment
spec:
  relicas: 2
  selector:
    matchLabels:
      app: redisdemo
   template:
      metadata:
        labels:
          app: redisdemo
