apiVersion: v1
kind: Deployment
metadata: 
  name: redis-deployment
spec:
  relicas: 2
  selector:
    matchLabels:
      app: redis
   template:
      metadata:
        labels:
          app: redis
      spec:
      containers:
        - name: k8s-demo
          image: redis
          ports:
            - name: nodejs-port
              containerPort: 3000
